import type { ServicePageContent } from "@/components/site/ServicePageLayout";

export const patientScreeningPage: ServicePageContent = {
  crumb: "Patient Screening",
  kicker: "Patient screening services",
  formService: "Patient Screening",
  seo: {
    title: "Patient Screening Services | Safer Intake | HS Partners",
    description: "Pre-visit patient screening services that organize intake, flag risk, and give clinicians the right information before every appointment. Book a free workflow review.",
    keywords: "patient screening services, pre-visit screening, patient intake screening, healthcare screening support, medical intake services, patient registration screening",
  },
  hero: {
    h1: "Patient Screening Services That Protect Patients and",
    h1Accent: "Prepare Your Team",
    intro: "Missed history, incomplete intake, and last-minute paperwork slow clinics down and put patients at risk. HS Partners provides structured patient screening services that collect, verify, and organize the right information before the visit so clinicians can start care with confidence.",
    primaryCta: "Request a Screening Review",
    secondaryCta: "Talk to an Intake Specialist",
  },
  about: {
    kicker: "Better decisions begin here",
    title: "What Is",
    titleAccent: "Patient Screening?",
    paragraphs: [
      "Patient screening is the process of collecting medical history, symptoms, medications, allergies, insurance details, and risk factors before a clinician sees the patient. Done well, it reduces wait times, prevents incomplete charts, and helps teams identify urgent cases earlier.",
      "When screening is handled at the front desk under pressure, details get missed. HS Partners gives your clinic a dedicated intake team, standardized questionnaires, and clear escalation rules so every visit starts with complete, usable information.",
    ],
  },
  offerings: {
    kicker: "Pre-visit to follow-up",
    title: "Our Patient Screening",
    titleAccent: "Services",
    intro: "We handle the full intake workflow, not just a form on the way in.",
    items: [
      { title: "Pre-Visit Intake and History", description: "We collect chief complaint, medical history, medications, allergies, and social history before the appointment so charts are ready when the patient arrives.", icon: "ClipboardCheck" },
      { title: "Insurance and Eligibility Checks", description: "Coverage, copays, and authorization needs are verified during screening so financial surprises do not delay care.", icon: "CircleDollarSign" },
      { title: "Risk and Symptom Flagging", description: "Structured questions help identify red-flag symptoms, infection risk, fall risk, and other concerns that need faster clinical attention.", icon: "HeartPulse" },
      { title: "Consent and Form Completion", description: "HIPAA acknowledgements, consents, and practice forms are completed digitally so the front desk is not chasing paperwork.", icon: "FileCheck2" },
      { title: "Medication and Allergy Review", description: "We confirm current medications and allergies and highlight discrepancies for the clinical team before the encounter.", icon: "ShieldCheck" },
      { title: "New Patient Onboarding", description: "First-visit packets, ID collection, and referral details are organized so new patients are fully registered before they sit down.", icon: "UserRoundCheck" },
      { title: "Recall and Follow-Up Screening", description: "We support recall lists, post-visit check-ins, and return-visit questionnaires so continuity of care does not depend on memory.", icon: "RefreshCcw" },
      { title: "Clinic-Specific Protocols", description: "Screening scripts are tailored to your specialty, payer mix, and visit types instead of one generic intake form.", icon: "Settings2" },
      { title: "Reporting and Quality Checks", description: "You see completion rates, missing-data trends, and turnaround times so intake quality stays visible.", icon: "BarChart3" },
    ],
  },
  process: {
    title: "Our Patient Screening Process:",
    titleAccent: "Step by Step",
    steps: [
      { number: "01", title: "Workflow review", description: "We map your current intake, bottlenecks, and the information clinicians actually need." },
      { number: "02", title: "Protocol design", description: "Question sets, escalation rules, and visit-type scripts are built around your specialty." },
      { number: "03", title: "System setup", description: "We connect to your EHR, intake forms, and phone or SMS reminders, usually within 7 days." },
      { number: "04", title: "Pre-visit outreach", description: "Patients are contacted before the appointment to complete screening and documents." },
      { number: "05", title: "Quality review", description: "Incomplete or high-risk responses are flagged and sent to the right team member." },
      { number: "06", title: "Chart preparation", description: "Clean intake is posted into the record before the clinician opens the encounter." },
      { number: "07", title: "Day-of support", description: "Same-day arrivals and walk-ins still get structured screening instead of rushed notes." },
      { number: "08", title: "Follow-up capture", description: "Recall and post-visit information is collected so nothing sits in a voicemail inbox." },
      { number: "09", title: "Monthly optimization", description: "A dedicated manager reviews completion rates and tightens the questions that cause drop-off." },
    ],
  },
  why: {
    title: "Why Clinics Choose",
    titleAccent: "HS Partners",
    note: "Your clinicians stay focused on care. We stay focused on complete intake.",
    items: [
      { title: "Specialty-ready scripts", description: "Primary care, specialty, and urgent workflows get different questions, not a copied template.", icon: "ClipboardCheck" },
      { title: "Clear escalation paths", description: "High-risk answers go to the right nurse or provider instead of sitting in a form.", icon: "HeartPulse" },
      { title: "HIPAA-conscious intake", description: "Patient data is collected through secure channels with role-based access.", icon: "Lock" },
      { title: "Works inside your EHR", description: "We do not force a new patient portal unless you want one.", icon: "Layers3" },
      { title: "Named account manager", description: "You have one owner for scripts, quality, and staffing.", icon: "BadgeCheck" },
      { title: "No long lock-in", description: "We earn the work every month with visible completion and wait-time gains.", icon: "ShieldCheck" },
    ],
  },
  results: {
    title: "Intake Targets We Work Toward",
    caption: "Industry intake benchmarks versus HS Partners screening targets",
    note: "Targets vary by specialty, visit mix, and how patients prefer to complete forms.",
    averageLabel: "Typical Clinic Baseline",
    targetLabel: "Our Target for Your Clinic",
    rows: [
      { metric: "Pre-visit form completion", average: "45–60%", target: "85%+" },
      { metric: "Missing chart data at visit", average: "High", target: "Materially reduced" },
      { metric: "Average check-in time", average: "12–18 min", target: "Under 8 min" },
      { metric: "Same-day paperwork chase", average: "Common", target: "Exception only" },
    ],
  },
  audiences: {
    kicker: "Built for real clinics",
    title: "Patient Screening Support",
    titleAccent: "by Setting",
    intro: "Different care settings need different questions, timing, and escalation rules.",
    items: [
      "Primary care and family medicine",
      "Specialty clinics",
      "Urgent care centers",
      "Behavioral health practices",
      "Pediatric offices",
      "Multi-location groups",
    ],
  },
  platforms: {
    kicker: "Fits your current tools",
    title: "EHR and Intake",
    titleAccent: "Integrations",
    intro: "We work inside the systems you already use for scheduling and charts.",
    items: ["Epic", "Athenahealth", "eClinicalWorks", "NextGen", "Tebra", "DrChrono", "Practice Fusion", "AdvancedMD"],
  },
  trust: {
    kicker: "Privacy first",
    title: "Secure Screening You Can",
    titleAccent: "Trust",
    body: "Patient screening includes sensitive health information. HS Partners follows HIPAA requirements, uses encrypted communication, limits access by role, and can sign a Business Associate Agreement. Screening scripts are reviewed so we collect only what your care team needs.",
  },
  pricing: {
    title: "How Much Do Patient Screening Services",
    titleAccent: "Cost?",
    body: "Pricing depends on visit volume, hours of coverage, and whether you need phone, SMS, and bilingual support. HS Partners offers hybrid monthly and per-visit pricing with no hidden setup fees. You see the scope in writing before we start.",
    cta: "Request a Custom Quote",
  },
  start: {
    steps: [
      { number: "01", title: "Share your intake gaps", description: "Tell us where forms stall, what clinicians still have to ask, and which visit types hurt most." },
      { number: "02", title: "Get a workflow review", description: "We show the screening steps that will cut check-in time and missing data." },
      { number: "03", title: "Go live", description: "We onboard your scripts and team, usually within 7 days." },
    ],
    closerTitle: "Ready for Complete Charts Before Every Visit?",
    closerCta: "Schedule Your Screening Review",
  },
  faq: {
    titleAccent: "patient screening.",
    items: [
      { question: "What do patient screening services include?", answer: "They typically include pre-visit intake, medical history collection, medication and allergy review, insurance checks, consent forms, risk flagging, and chart preparation before the appointment." },
      { question: "Is patient screening the same as check-in?", answer: "Check-in is the front-desk arrival process. Screening happens earlier and goes deeper: clinical history, risk questions, and document completion so the visit is ready before the patient walks in." },
      { question: "Can you screen patients by phone and text?", answer: "Yes. We use the channels your patients actually respond to, including phone, SMS, and secure forms, then follow up on incomplete responses." },
      { question: "Do you work with our existing EHR?", answer: "Yes. We work with major EHR and practice management platforms and post completed intake into your current workflow." },
      { question: "How do you handle high-risk answers?", answer: "We agree escalation rules with your clinical lead. Urgent symptoms, infection concerns, or safety flags are routed immediately instead of waiting in a queue." },
      { question: "Is this HIPAA compliant?", answer: "Yes. We follow HIPAA privacy and security requirements, sign a BAA when needed, and limit who can see patient information." },
      { question: "How quickly can we start?", answer: "Most clinics begin after a short workflow review and system access. Setup is usually complete within 7 days." },
      { question: "Will this replace our front desk?", answer: "No. It removes incomplete paperwork and phone tag so your front desk can focus on patients who are already in the building." },
    ],
  },
  related: [
    { label: "Medical Billing", href: "/medical-billing-services" },
    { label: "Appointments", href: "/appointment-scheduling-services" },
    { label: "Ultrasound Services", href: "/ultrasound-services" },
  ],
};

export const ultrasoundPage: ServicePageContent = {
  crumb: "Ultrasound Services",
  kicker: "Ultrasound coordination services",
  formService: "Ultrasound Services",
  seo: {
    title: "Ultrasound Services | Faster Imaging Support | HS Partners",
    description: "Ultrasound scheduling, patient prep, and results coordination that reduce no-shows and keep imaging workflows moving. Get a free operations review from HS Partners.",
    keywords: "ultrasound services, ultrasound scheduling, diagnostic ultrasound support, sonography coordination, imaging appointment services, ultrasound patient coordination",
  },
  hero: {
    h1: "Ultrasound Services That Keep Imaging",
    h1Accent: "On Time and Clear",
    intro: "Open slots, unprepared patients, and delayed reports waste capacity and delay care. HS Partners coordinates ultrasound services around patients, sonographers, and referring clinicians so every study is scheduled, prepared, and followed through.",
    primaryCta: "Review Your Imaging Workflow",
    secondaryCta: "Talk to an Ultrasound Coordinator",
  },
  about: {
    kicker: "Care in every detail",
    title: "What Are Coordinated",
    titleAccent: "Ultrasound Services?",
    paragraphs: [
      "Ultrasound coordination covers more than booking a room. It includes order review, patient preparation, insurance or authorization checks, reminder calls, day-of support, and results follow-up so studies are completed the first time.",
      "When this work sits on already busy clinical staff, no-shows rise and reports stall. HS Partners gives imaging teams a dedicated coordination layer that protects scanner time and improves the patient experience.",
    ],
  },
  offerings: {
    kicker: "From order to result",
    title: "Our Ultrasound",
    titleAccent: "Services",
    intro: "We support the full imaging journey, not just the calendar.",
    items: [
      { title: "Order Intake and Protocol Checks", description: "We confirm the study type, laterality, clinical indication, and any missing details before the appointment is locked.", icon: "FileCheck2" },
      { title: "Ultrasound Scheduling", description: "Slots are booked around machine time, sonographer availability, and patient constraints such as fasting or bladder prep.", icon: "CalendarCheck" },
      { title: "Patient Preparation Guidance", description: "Clear prep instructions are given in the patient's language and confirmed before the visit to reduce incomplete studies.", icon: "MessagesSquare" },
      { title: "Authorization and Benefits Support", description: "Where imaging needs prior approval, we gather documentation and track status so the appointment is not cancelled at the door.", icon: "CircleDollarSign" },
      { title: "Reminder and No-Show Recovery", description: "Multi-touch reminders and same-day backfill help keep expensive ultrasound time filled.", icon: "Clock3" },
      { title: "Day-of Patient Coordination", description: "Arrival checks, late arrivals, and add-on requests are managed so the list stays realistic.", icon: "UserRoundCheck" },
      { title: "Results and Report Follow-Up", description: "We track pending reads and help referring offices know when reports are ready.", icon: "RefreshCcw" },
      { title: "Referring Provider Liaison", description: "Clinics sending patients get one reliable channel for orders, status, and reschedules.", icon: "HeartPulse" },
      { title: "Capacity and Utilization Reporting", description: "You see fill rate, no-show rate, and turnaround so staffing decisions are based on data.", icon: "BarChart3" },
    ],
  },
  process: {
    title: "Our Ultrasound Coordination Process:",
    titleAccent: "Step by Step",
    steps: [
      { number: "01", title: "Capacity review", description: "We look at machine hours, peak days, and where studies are delayed or cancelled." },
      { number: "02", title: "Order standardization", description: "Required fields and prep rules are defined for each ultrasound type." },
      { number: "03", title: "Calendar setup", description: "We connect to your scheduling system and build fill rules, usually within 7 days." },
      { number: "04", title: "Patient booking", description: "Orders are converted into prepared appointments with confirmed instructions." },
      { number: "05", title: "Pre-visit confirmation", description: "Prep, location, and coverage are reconfirmed 24–48 hours before the study." },
      { number: "06", title: "Day-of list management", description: "Arrivals, delays, and add-ons are coordinated with the sonography team." },
      { number: "07", title: "Study completion tracking", description: "Incomplete or rescheduled cases are worked the same day." },
      { number: "08", title: "Report follow-through", description: "Pending results are tracked until the referring clinician has what they need." },
      { number: "09", title: "Monthly optimization", description: "We review no-shows, unused slots, and prep failures and adjust the playbook." },
    ],
  },
  why: {
    title: "Why Imaging Teams Choose",
    titleAccent: "HS Partners",
    note: "Your sonographers scan. We keep the list full and patients prepared.",
    items: [
      { title: "Prep that patients actually follow", description: "Instructions are specific to the study, not a generic reminder.", icon: "ClipboardCheck" },
      { title: "Protected machine time", description: "We treat unused ultrasound slots as lost revenue and lost care.", icon: "Clock3" },
      { title: "Referring clinics stay informed", description: "Status updates reduce the 'where is the report?' phone spiral.", icon: "MessagesSquare" },
      { title: "HIPAA-safe coordination", description: "Orders and results are handled through secure, role-limited access.", icon: "Lock" },
      { title: "Works with your RIS or EHR", description: "No forced software switch for scheduling or documentation.", icon: "Layers3" },
      { title: "Named imaging coordinator", description: "One owner for the list, not a rotating inbox.", icon: "BadgeCheck" },
    ],
  },
  results: {
    title: "Imaging Targets We Work Toward",
    caption: "Typical ultrasound operations metrics versus HS Partners targets",
    note: "Targets vary by study mix, walk-in volume, and whether authorization is required.",
    averageLabel: "Typical Imaging Baseline",
    targetLabel: "Our Target for Your Center",
    rows: [
      { metric: "Appointment no-show rate", average: "12–18%", target: "Under 8%" },
      { metric: "Incomplete studies from poor prep", average: "Recurring", target: "Rare" },
      { metric: "Slot utilization", average: "Inconsistent", target: "High and predictable" },
      { metric: "Report follow-up lag", average: "Days of chasing", target: "Tracked to close" },
    ],
  },
  audiences: {
    kicker: "For every imaging setting",
    title: "Ultrasound Support",
    titleAccent: "by Facility",
    intro: "Hospital departments, outpatient centers, and specialty clinics all lose time in different places.",
    items: [
      "Outpatient imaging centers",
      "OB/GYN and women's health",
      "Vascular and cardiac ultrasound",
      "Hospital radiology departments",
      "Urgent care imaging",
      "Mobile ultrasound programs",
    ],
  },
  platforms: {
    kicker: "Scheduling you already have",
    title: "Systems We",
    titleAccent: "Work Inside",
    intro: "We coordinate through your existing EHR, RIS, or practice calendar.",
    items: ["Epic", "Athenahealth", "eClinicalWorks", "NextGen", "Meditech", "Tebra", "Google Calendar / PM tools"],
  },
  trust: {
    kicker: "Clinical information protected",
    title: "Compliant Imaging Support You Can",
    titleAccent: "Trust",
    body: "Ultrasound orders and results are protected health information. HS Partners follows HIPAA requirements, uses encrypted channels, and limits access to the coordinators assigned to your account. We do not interpret images; we keep the operational path around the study clean and complete.",
  },
  pricing: {
    title: "How Much Do Ultrasound Coordination Services",
    titleAccent: "Cost?",
    body: "Pricing depends on study volume, hours of coverage, and whether you need authorization support. HS Partners offers monthly or per-study hybrid pricing with a written scope and no surprise onboarding fees.",
    cta: "Request a Custom Quote",
  },
  start: {
    steps: [
      { number: "01", title: "Show us the schedule gaps", description: "Share no-show patterns, unused slots, and the studies that need the most prep." },
      { number: "02", title: "Receive an operations review", description: "We outline how coordination will protect machine time and patient prep." },
      { number: "03", title: "Go live", description: "We connect to your calendar and start filling a cleaner list, usually within 7 days." },
    ],
    closerTitle: "Ready to Stop Losing Ultrasound Slots?",
    closerCta: "Schedule Your Imaging Review",
  },
  faq: {
    titleAccent: "ultrasound services.",
    items: [
      { question: "Do you perform the ultrasound exams?", answer: "No. HS Partners coordinates scheduling, patient prep, authorizations, and follow-up. Your credentialed sonographers and interpreting physicians perform and read the studies." },
      { question: "What types of ultrasound can you support?", answer: "We support general, OB/GYN, vascular, small-parts, and other outpatient or hospital lists as long as your team defines the protocols." },
      { question: "Can you reduce no-shows?", answer: "Yes. Multi-touch reminders, prep confirmation, and same-day backfill are built into the process because unused slots are expensive." },
      { question: "Do you handle prior authorization?", answer: "Where a study needs approval, we gather clinical details and track the authorization so the appointment is not cancelled on arrival." },
      { question: "Will patients still call our clinic?", answer: "They can, but most scheduling and prep questions can be handled by our coordinators using your scripts and hours." },
      { question: "Is the service HIPAA compliant?", answer: "Yes. Orders, demographics, and results status are handled under HIPAA rules with a BAA when required." },
      { question: "How fast can we start?", answer: "After calendar access and protocol review, most teams go live within 7 days." },
      { question: "Can you work with referring clinics?", answer: "Yes. Referring offices get a clear channel for orders, reschedules, and report status." },
    ],
  },
  related: [
    { label: "X-Ray Services", href: "/x-ray-services" },
    { label: "Patient Screening", href: "/patient-screening-services" },
    { label: "Appointments", href: "/appointment-scheduling-services" },
  ],
};

export const xrayPage: ServicePageContent = {
  crumb: "X-Ray Services",
  kicker: "X-ray coordination services",
  formService: "X-Ray Services",
  seo: {
    title: "X-Ray Services | Faster Diagnostic Imaging | HS Partners",
    description: "X-ray scheduling, patient coordination, and diagnostic imaging support that reduce delays and keep radiology workflows moving. Book a free operations review.",
    keywords: "x-ray services, diagnostic imaging coordination, radiology scheduling, x-ray appointment services, imaging patient support, outpatient x-ray services",
  },
  hero: {
    h1: "X-Ray Services That Deliver Clarity",
    h1Accent: "Without the Delay",
    intro: "Walk-ins, missing orders, and unprepared patients stall radiology lists. HS Partners coordinates X-ray services with dependable scheduling, patient communication, and follow-through so diagnostic imaging stays fast, accurate, and easy for referring teams.",
    primaryCta: "Review Your X-Ray Workflow",
    secondaryCta: "Talk to an Imaging Specialist",
  },
  about: {
    kicker: "Clarity you can trust",
    title: "What Do Coordinated",
    titleAccent: "X-Ray Services Include?",
    paragraphs: [
      "X-ray coordination covers order intake, laterality checks, pregnancy and safety screening questions, scheduling, arrival management, and results routing. The clinical exam stays with your technologists and radiologists. The operational chaos does not.",
      "Practices lose hours when staff juggle phones, paper orders, and same-day add-ons. HS Partners gives you a dedicated imaging desk that keeps the list honest and patients informed.",
    ],
  },
  offerings: {
    kicker: "Order to report",
    title: "Our X-Ray",
    titleAccent: "Services",
    intro: "We keep diagnostic imaging moving from the first order to the final report handoff.",
    items: [
      { title: "Order Review and Laterality Checks", description: "We confirm exam type, body part, and clinical indication so the wrong study is not booked.", icon: "FileCheck2" },
      { title: "X-Ray Scheduling", description: "Walk-in rules, timed slots, and add-ons are balanced so the room is used without overloading techs.", icon: "CalendarCheck" },
      { title: "Safety and Screening Questions", description: "Pregnancy status, recent studies, and mobility needs are captured before the patient arrives.", icon: "ShieldCheck" },
      { title: "Insurance and Authorization Support", description: "When coverage or approval is required, we handle the paperwork before the patient is on the table.", icon: "CircleDollarSign" },
      { title: "Patient Arrival Coordination", description: "Late arrivals, wheelchair needs, and pediatric accompaniment are planned instead of discovered at the door.", icon: "UserRoundCheck" },
      { title: "Referring Clinic Communication", description: "Urgent findings pathways and routine report delivery are tracked so callers are not left guessing.", icon: "MessagesSquare" },
      { title: "Stat and Same-Day Add-Ons", description: "We apply your priority rules so true stats jump the list and elective add-ons do not wreck the day.", icon: "Clock3" },
      { title: "Repeat and Comparison Study Support", description: "Prior images and comparison needs are noted so the radiologist is not missing context.", icon: "RefreshCcw" },
      { title: "Utilization Reporting", description: "Volume, wait time, and cancellation reasons stay visible for staffing and equipment decisions.", icon: "BarChart3" },
    ],
  },
  process: {
    title: "Our X-Ray Coordination Process:",
    titleAccent: "Step by Step",
    steps: [
      { number: "01", title: "List review", description: "We study walk-in volume, peak hours, and where orders arrive incomplete." },
      { number: "02", title: "Rule design", description: "Stat, same-day, and scheduled rules are written with your lead technologist." },
      { number: "03", title: "System access", description: "We connect to your RIS, EHR, or schedule, usually within 7 days." },
      { number: "04", title: "Order capture", description: "Incoming orders are checked for completeness before a slot is promised." },
      { number: "05", title: "Patient confirmation", description: "Time, location, and any prep or safety questions are confirmed in advance." },
      { number: "06", title: "Day-of flow", description: "Arrivals and add-ons are coordinated so the room stays productive." },
      { number: "07", title: "Exception handling", description: "No-shows, wrong orders, and safety holds are resolved with a documented next step." },
      { number: "08", title: "Report routing", description: "Completed studies are tracked until the referring clinician has the result." },
      { number: "09", title: "Monthly tuning", description: "Wait times and cancellation reasons are reviewed and the rules are tightened." },
    ],
  },
  why: {
    title: "Why Radiology Teams Choose",
    titleAccent: "HS Partners",
    note: "Your technologists image. We keep the order, the patient, and the report aligned.",
    items: [
      { title: "Fewer wrong-study bookings", description: "Laterality and indication checks happen before the patient is in the room.", icon: "FileCheck2" },
      { title: "Honest wait times", description: "We do not overbook to look available and then apologize in the lobby.", icon: "Clock3" },
      { title: "Clear stat rules", description: "True emergencies move first because the criteria are written down.", icon: "Radio" },
      { title: "HIPAA-safe messaging", description: "Orders and results status stay on approved channels.", icon: "Lock" },
      { title: "Fits your RIS", description: "We work in the system your techs already open every morning.", icon: "Layers3" },
      { title: "Dedicated imaging desk", description: "Referring clinics get one number that actually knows the list.", icon: "BadgeCheck" },
    ],
  },
  results: {
    title: "Diagnostic Imaging Targets We Work Toward",
    caption: "Typical X-ray operations metrics versus HS Partners targets",
    note: "Targets vary by walk-in share, trauma volume, and whether studies are scheduled or open-access.",
    averageLabel: "Typical Radiology Baseline",
    targetLabel: "Our Target for Your Department",
    rows: [
      { metric: "Incomplete orders at booking", average: "Frequent", target: "Caught before arrival" },
      { metric: "Patient wait-time surprises", average: "Common", target: "Communicated early" },
      { metric: "Same-day list chaos", average: "High", target: "Rule-based and calm" },
      { metric: "Report status calls", average: "Constant", target: "Proactively updated" },
    ],
  },
  audiences: {
    kicker: "Across care settings",
    title: "X-Ray Support",
    titleAccent: "by Environment",
    intro: "Urgent care, orthopedic clinics, and hospital departments all need different list rules.",
    items: [
      "Urgent care and walk-in clinics",
      "Orthopedic and sports medicine",
      "Hospital radiology",
      "Occupational health",
      "Pediatric imaging",
      "Multi-site outpatient groups",
    ],
  },
  platforms: {
    kicker: "No new radiology stack required",
    title: "RIS and EHR",
    titleAccent: "Integrations",
    intro: "We coordinate inside the tools your imaging team already uses.",
    items: ["Epic", "Meditech", "eClinicalWorks", "NextGen", "Athenahealth", "PACS-adjacent workflows"],
  },
  trust: {
    kicker: "Safety and privacy",
    title: "Responsible Imaging Coordination You Can",
    titleAccent: "Trust",
    body: "X-ray coordination includes safety screening and protected health information. HS Partners follows HIPAA requirements, documents escalation for urgent findings according to your protocol, and never substitutes operational staff for licensed technologists or radiologists.",
  },
  pricing: {
    title: "How Much Do X-Ray Coordination Services",
    titleAccent: "Cost?",
    body: "Pricing depends on daily volume, walk-in share, and hours of coverage. HS Partners offers monthly or volume-based hybrid pricing with a clear written scope and no hidden setup charges.",
    cta: "Request a Custom Quote",
  },
  start: {
    steps: [
      { number: "01", title: "Walk us through a typical list", description: "Share how orders arrive, how stats are handled, and where the day usually breaks." },
      { number: "02", title: "Get an operations review", description: "We show which rules will reduce wait-time chaos and incomplete studies." },
      { number: "03", title: "Go live", description: "Your imaging desk is staffed and connected, usually within 7 days." },
    ],
    closerTitle: "Ready for a Calmer, Faster X-Ray List?",
    closerCta: "Schedule Your Imaging Review",
  },
  faq: {
    titleAccent: "X-ray services.",
    items: [
      { question: "Do you take the X-rays?", answer: "No. Licensed radiologic technologists acquire images and radiologists interpret them. HS Partners handles scheduling, patient coordination, order quality, and report follow-up." },
      { question: "Can you support walk-in X-ray?", answer: "Yes. We can run open-access rules, estimated wait communication, and add-on control so walk-in volume does not overwhelm the room." },
      { question: "How do you prevent the wrong exam being booked?", answer: "Orders are checked for exam type, laterality, and indication before a time is confirmed. Ambiguous orders go back to the referring clinic immediately." },
      { question: "Do you handle stat studies?", answer: "Yes. We follow your written stat criteria so urgent cases move first and everything else stays in a realistic order." },
      { question: "Is this HIPAA compliant?", answer: "Yes. Demographics, orders, and results status are handled under HIPAA with a BAA when required." },
      { question: "Will this work with our RIS?", answer: "We work with common EHR and RIS platforms and adapt to the scheduling view your techs already use." },
      { question: "How quickly can we start?", answer: "Most departments go live within 7 days of access and protocol review." },
      { question: "Can orthopedic or urgent care clinics use this?", answer: "Yes. High same-day volume is one of the settings where dedicated X-ray coordination pays off fastest." },
    ],
  },
  related: [
    { label: "Ultrasound Services", href: "/ultrasound-services" },
    { label: "Patient Screening", href: "/patient-screening-services" },
    { label: "Medical Billing", href: "/medical-billing-services" },
  ],
};

export const leadManagementPage: ServicePageContent = {
  crumb: "Lead Management",
  kicker: "Lead management services",
  formService: "Lead Management",
  seo: {
    title: "Lead Management Services | Faster Follow-Up | HS Partners",
    description: "Outsourced lead management that captures, qualifies, and nurtures every enquiry so sales teams close more of the demand they already paid for. Book a free pipeline review.",
    keywords: "lead management services, outsourced lead management, lead qualification, enquiry follow-up, sales lead nurturing, inbound lead management",
  },
  hero: {
    h1: "Lead Management Services That Turn Enquiries Into",
    h1Accent: "Qualified Conversations",
    intro: "Most companies do not have a lead problem. They have a follow-up problem. HS Partners captures, qualifies, and nurtures every enquiry with speed and discipline so your closers spend time on buyers, not cold inboxes.",
    primaryCta: "Get a Pipeline Review",
    secondaryCta: "Talk to a Lead Specialist",
  },
  about: {
    kicker: "Every inquiry, handled",
    title: "What Is",
    titleAccent: "Lead Management?",
    paragraphs: [
      "Lead management is the system for receiving, scoring, contacting, and progressing prospects from first enquiry to a sales-ready conversation. It includes speed-to-lead, qualification, appointment setting, and recycle of leads that are not ready yet.",
      "When this sits with busy salespeople, new leads wait while warm deals are closed. By the time someone calls back, the buyer has chosen someone faster. HS Partners gives you a dedicated response team that works the top of the funnel every hour it is open.",
    ],
  },
  offerings: {
    kicker: "Capture to handover",
    title: "Our Lead Management",
    titleAccent: "Services",
    intro: "We run the full front of the funnel, not a once-a-day callback list.",
    items: [
      { title: "Multi-Channel Lead Capture", description: "Web forms, ads, chat, phone, and marketplace leads are pulled into one queue with source tags intact.", icon: "Target" },
      { title: "Speed-to-Lead Response", description: "New enquiries are contacted in minutes, not the next business afternoon, while intent is still high.", icon: "Clock3" },
      { title: "Qualification and Scoring", description: "Budget, timeline, fit, and authority are confirmed against your criteria before a closer is involved.", icon: "ClipboardCheck" },
      { title: "Appointment Setting", description: "Qualified prospects are booked directly onto the right calendar with context the salesperson can use.", icon: "CalendarCheck" },
      { title: "Nurture and Recycle", description: "Not-now leads stay in a structured follow-up cadence instead of dying in a spreadsheet.", icon: "RefreshCcw" },
      { title: "CRM Hygiene", description: "Duplicates, missing fields, and stale stages are cleaned so reporting matches reality.", icon: "Settings2" },
      { title: "Script and Offer Testing", description: "Talk tracks and first-touch messages are refined based on connect rates and booked meetings.", icon: "MessagesSquare" },
      { title: "After-Hours Coverage", description: "Evening and weekend enquiries still get a human response instead of an autoresponder graveyard.", icon: "Layers3" },
      { title: "Pipeline Reporting", description: "You see source quality, speed-to-lead, connect rate, and show rate every week.", icon: "BarChart3" },
    ],
  },
  process: {
    title: "Our Lead Management Process:",
    titleAccent: "Step by Step",
    steps: [
      { number: "01", title: "Funnel audit", description: "We review sources, response times, and where qualified demand is leaking." },
      { number: "02", title: "Scorecard design", description: "Your ideal customer, disqualify rules, and appointment criteria are written down." },
      { number: "03", title: "CRM and routing setup", description: "Leads flow into one queue with owners and SLAs, usually within 7 days." },
      { number: "04", title: "First-touch coverage", description: "New leads are called, texted, or emailed according to the channel they used." },
      { number: "05", title: "Qualification", description: "Fit is confirmed and notes are written for the closer, not just a 'hot' tag." },
      { number: "06", title: "Meeting booked", description: "The right calendar is offered and reminders are sent to protect show rate." },
      { number: "07", title: "Handover", description: "Sales gets context, recordings or notes, and a clean next step." },
      { number: "08", title: "Nurture", description: "Unready leads stay in a cadence until they re-engage or age out." },
      { number: "09", title: "Weekly optimization", description: "Source quality and talk tracks are reviewed with your sales lead." },
    ],
  },
  why: {
    title: "Why Growth Teams Choose",
    titleAccent: "HS Partners",
    note: "Your closers close. We make sure they are not the first human the lead ever hears from two days late.",
    items: [
      { title: "Minutes, not days", description: "Speed-to-lead is treated as a service level, not a hope.", icon: "Clock3" },
      { title: "Your qualification rules", description: "We do not book junk meetings to look busy.", icon: "ClipboardCheck" },
      { title: "Source-level honesty", description: "You see which ads and forms create conversations, not just clicks.", icon: "BarChart3" },
      { title: "CRM you already own", description: "HubSpot, Salesforce, Zoho, or sheets — we work in your system of record.", icon: "Layers3" },
      { title: "Named pod, not a ticket", description: "The same specialists learn your offer and objections.", icon: "BadgeCheck" },
      { title: "No long lock-in", description: "If booked meetings and show rates do not improve, you should not stay.", icon: "ShieldCheck" },
    ],
  },
  results: {
    title: "Pipeline Targets We Work Toward",
    caption: "Typical inbound follow-up metrics versus HS Partners targets",
    note: "Targets vary by industry, lead source quality, and whether you sell high-ticket or high-volume offers.",
    averageLabel: "Typical Inbound Baseline",
    targetLabel: "Our Target for Your Team",
    rows: [
      { metric: "First response time", average: "Hours to days", target: "Minutes during coverage" },
      { metric: "Touched but never qualified", average: "High", target: "Every lead dispositioned" },
      { metric: "Sales time on junk leads", average: "Too much", target: "Protected for closers" },
      { metric: "Show rate on set meetings", average: "Inconsistent", target: "Reminded and confirmed" },
    ],
  },
  audiences: {
    kicker: "For teams that already generate demand",
    title: "Lead Management",
    titleAccent: "by Industry",
    intro: "The process is the same. The qualification questions are not.",
    items: [
      "Healthcare and clinic groups",
      "Home services and trades",
      "B2B professional services",
      "Education and training",
      "Real estate and mortgage",
      "SaaS and local services",
    ],
  },
  platforms: {
    kicker: "Works with your stack",
    title: "CRM and Ad",
    titleAccent: "Integrations",
    intro: "We meet leads in the tools you already paid for.",
    items: ["HubSpot", "Salesforce", "Zoho", "Pipedrive", "GoHighLevel", "Meta Ads", "Google Ads", "Call tracking"],
  },
  trust: {
    kicker: "Brand-safe conversations",
    title: "Lead Handling You Can",
    titleAccent: "Stand Behind",
    body: "Your brand is on the first call. HS Partners uses approved scripts, records or logs activity in your CRM, and never invents pricing or promises. Where healthcare or financial leads are involved, we follow the privacy rules you specify.",
  },
  pricing: {
    title: "How Much Do Lead Management Services",
    titleAccent: "Cost?",
    body: "Pricing depends on lead volume, coverage hours, and number of sources. HS Partners offers monthly pods or per-qualified-appointment hybrid pricing. Setup, reporting, and CRM work are stated upfront.",
    cta: "Request a Custom Quote",
  },
  start: {
    steps: [
      { number: "01", title: "Show us the leak", description: "Share response times, source mix, and how many leads never get a real conversation." },
      { number: "02", title: "Get a pipeline review", description: "We show where speed, qualification, or nurture will recover the most revenue." },
      { number: "03", title: "Go live", description: "Your queue is staffed and SLAs start, usually within 7 days." },
    ],
    closerTitle: "Ready to Stop Paying for Leads You Never Call?",
    closerCta: "Schedule Your Pipeline Review",
  },
  faq: {
    titleAccent: "lead management.",
    items: [
      { question: "What is included in lead management services?", answer: "Capture, rapid first response, qualification, appointment setting, CRM updates, nurture of unready leads, and reporting on source quality and speed-to-lead." },
      { question: "Will you replace my sales team?", answer: "No. We work the top of the funnel so closers receive qualified conversations instead of raw form fills." },
      { question: "How fast do you respond to new leads?", answer: "During agreed coverage hours we aim for first contact in minutes. After-hours coverage can be added if your sources run 24/7." },
      { question: "Do you work inside our CRM?", answer: "Yes. We use your HubSpot, Salesforce, Zoho, or similar system so you keep the data." },
      { question: "What if a lead is not ready to buy?", answer: "They are dispositioned honestly and placed in a nurture cadence instead of being marked lost or ignored." },
      { question: "Can you handle inbound calls and web forms?", answer: "Yes. Multi-channel queues are the default, with source tags so you can see what actually converts." },
      { question: "How do you protect our brand on the phone?", answer: "Approved scripts, recorded or logged outcomes, and no unofficial discounts or claims." },
      { question: "How quickly can we start?", answer: "Most teams go live within 7 days of CRM access and scorecard approval." },
    ],
  },
  related: [
    { label: "Appointments", href: "/appointment-scheduling-services" },
    { label: "Fast Food Solutions", href: "/fast-food-solutions" },
    { label: "Medical Billing", href: "/medical-billing-services" },
  ],
};

export const truckDispatchingPage: ServicePageContent = {
  crumb: "Truck Dispatching",
  kicker: "Truck dispatching services",
  formService: "Truck Dispatching",
  seo: {
    title: "Truck Dispatching Services | Keep Trucks Moving | HS Partners",
    description: "Owner-operator and small fleet truck dispatching with load booking, rate negotiation, and 24/7 driver support. Get a free dispatch review from HS Partners.",
    keywords: "truck dispatching services, truck dispatcher, owner operator dispatch, freight dispatching, load booking services, trucking dispatch company",
  },
  hero: {
    h1: "Truck Dispatching Services That Keep Drivers",
    h1Accent: "Loaded and Informed",
    intro: "Deadhead, slow pay, and silent dispatchers cost more than a bad week. HS Partners provides truck dispatching services for owner-operators and small fleets: load search, rate negotiation, paperwork, and driver support so trucks stay moving and you stay in control of the freight you haul.",
    primaryCta: "Get a Dispatch Review",
    secondaryCta: "Talk to a Dispatcher",
  },
  about: {
    kicker: "Loads, routes, and support",
    title: "What Is",
    titleAccent: "Truck Dispatching?",
    paragraphs: [
      "Truck dispatching is the work of finding suitable loads, negotiating rate and detention terms, planning deadhead, handling broker communication, and staying with the driver from booking through delivery. It is the difference between a truck that earns and a truck that waits.",
      "Doing it yourself while driving is how details slip: bad lanes, unpaid detention, and hours wasted on hold. HS Partners assigns dispatchers who treat your preferences, home time, and equipment as non-negotiable.",
    ],
  },
  offerings: {
    kicker: "Booking to delivery",
    title: "Our Truck Dispatching",
    titleAccent: "Services",
    intro: "We cover the full load cycle, not a blast of load board screenshots.",
    items: [
      { title: "Load Search and Booking", description: "We search boards and broker networks for freight that matches your equipment, lanes, and rate floor.", icon: "Search" },
      { title: "Rate Negotiation", description: "We push for all-in rates, detention, and layover language instead of taking the first offer.", icon: "CircleDollarSign" },
      { title: "Route and Deadhead Planning", description: "Next loads are planned before you empty so unpaid miles stay visible and limited.", icon: "Truck" },
      { title: "Broker and Shipper Communication", description: "Check calls, appointment updates, and problem freight are handled so you can stay on the road.", icon: "MessagesSquare" },
      { title: "Paperwork and POD Follow-Up", description: "Rate cons, BOLs, and PODs are chased so invoicing is not waiting on a missing photo.", icon: "FileCheck2" },
      { title: "Detention and Accessorial Support", description: "We document delays and request accessorials while the facts are still fresh.", icon: "Clock3" },
      { title: "24/7 Driver Support", description: "Breakdowns, refused loads, and after-hours appointment changes get a human, not a voicemail.", icon: "RefreshCcw" },
      { title: "Compliance-Aware Dispatching", description: "HOS, weight, and equipment limits are respected. We do not book freight that puts your authority at risk.", icon: "ShieldCheck" },
      { title: "Weekly Performance Reporting", description: "You see loaded miles, rate per mile, deadhead, and unpaid time so dispatch quality is measurable.", icon: "BarChart3" },
    ],
  },
  process: {
    title: "Our Dispatch Process:",
    titleAccent: "Step by Step",
    steps: [
      { number: "01", title: "Truck and lane profile", description: "Equipment, preferred states, home time, and your rate floor are documented." },
      { number: "02", title: "Broker setup", description: "Packets, factoring, and approved broker lists are organized before the first booking." },
      { number: "03", title: "Go-live", description: "Your dispatcher starts covering the truck, usually within a few days of documents." },
      { number: "04", title: "Load options", description: "You approve freight that meets the profile. We do not force mystery loads." },
      { number: "05", title: "Booking and instructions", description: "Pickup, delivery, and special requirements are confirmed in writing." },
      { number: "06", title: "In-transit support", description: "Check calls, delays, and appointment changes are managed with the broker." },
      { number: "07", title: "Delivery close-out", description: "POD and accessorials are collected while the next load is already in motion." },
      { number: "08", title: "Settlement visibility", description: "You see what was hauled, what is outstanding, and what needs a dispute." },
      { number: "09", title: "Weekly reset", description: "Lanes, brokers, and rate trends are reviewed so the next week is smarter." },
    ],
  },
  why: {
    title: "Why Drivers and Fleets Choose",
    titleAccent: "HS Partners",
    note: "You keep the authority and the truck. We keep the phone and the board.",
    items: [
      { title: "Your rate floor is real", description: "We do not book cheap freight to look busy and then disappear.", icon: "CircleDollarSign" },
      { title: "Home time is planned", description: "Reset weeks are built into dispatch, not treated as an inconvenience.", icon: "CalendarCheck" },
      { title: "One dispatcher who knows the truck", description: "Continuity beats a random night person who has never seen your trailer type.", icon: "BadgeCheck" },
      { title: "After-hours coverage", description: "Problems at 2 a.m. still get handled.", icon: "Clock3" },
      { title: "Transparent percentage or hybrid", description: "You know the dispatch fee before the first load is booked.", icon: "Wallet" },
      { title: "No forced lease or factoring", description: "Use the factoring and insurance you already trust.", icon: "ShieldCheck" },
    ],
  },
  results: {
    title: "Dispatch Targets We Work Toward",
    caption: "Typical owner-operator pain points versus HS Partners dispatch targets",
    note: "Results depend on equipment, season, region, and the rate floor you set.",
    averageLabel: "Typical Solo Baseline",
    targetLabel: "Our Target for Your Truck",
    rows: [
      { metric: "Empty waiting between loads", average: "Unplanned days", target: "Next load booked earlier" },
      { metric: "Deadhead visibility", average: "After the fact", target: "Shown before you accept" },
      { metric: "Detention follow-up", average: "Forgotten", target: "Documented and requested" },
      { metric: "Driver admin time", average: "Hours on the phone", target: "Driving and rest" },
    ],
  },
  audiences: {
    kicker: "Built around the truck you run",
    title: "Dispatching",
    titleAccent: "by Equipment",
    intro: "Dry van, reefer, and flatbed need different boards, brokers, and appointment realities.",
    items: [
      "Owner-operators",
      "Small fleets (2–15 trucks)",
      "Dry van",
      "Reefer",
      "Flatbed and step deck",
      "Power-only where requested",
    ],
  },
  platforms: {
    kicker: "Boards and tools you already use",
    title: "Load Boards and",
    titleAccent: "Systems",
    intro: "We dispatch through the networks and factoring setups you approve.",
    items: ["DAT", "Truckstop", "Broker portals", "ELD / HOS awareness", "Factoring packets", "SMS / driver apps"],
  },
  trust: {
    kicker: "Your authority stays yours",
    title: "Dispatch You Can",
    titleAccent: "Control",
    body: "HS Partners does not take over your MC or force a lease-on. You approve freight, keep your customers if you have them, and see every rate confirmation. We communicate professionally with brokers because your reputation is the next load.",
  },
  pricing: {
    title: "How Much Do Truck Dispatching Services",
    titleAccent: "Cost?",
    body: "Most dispatchers charge a percentage of the load, often in the 5–10% range depending on equipment and support level. HS Partners uses transparent percentage or hybrid pricing with no surprise weekly minimums unless they are agreed in writing first.",
    cta: "Request Dispatch Pricing",
  },
  start: {
    steps: [
      { number: "01", title: "Tell us the truck", description: "Equipment, preferred lanes, home time, and the rate you will not go below." },
      { number: "02", title: "Packet and profile", description: "We set up broker documents and your dispatch preferences." },
      { number: "03", title: "Start booking", description: "Your dispatcher begins covering the truck once documents are in place." },
    ],
    closerTitle: "Ready for a Dispatcher Who Actually Stays on the Phone?",
    closerCta: "Schedule Your Dispatch Review",
  },
  faq: {
    titleAccent: "truck dispatching.",
    items: [
      { question: "Do I have to lease onto your authority?", answer: "No. We dispatch trucks that already have their own authority, insurance, and factoring unless you ask for a different arrangement." },
      { question: "How much do you charge?", answer: "Dispatch is typically a percentage of booked freight. The exact rate depends on equipment, volume, and whether you need 24/7 coverage. We state it before the first load." },
      { question: "Can I reject a load?", answer: "Yes. You set the rate floor and lane preferences. We present options; you decide." },
      { question: "Do you work nights and weekends?", answer: "Yes. After-hours support is part of keeping appointments and breakdowns from becoming unpaid days." },
      { question: "What equipment do you dispatch?", answer: "Dry van, reefer, flatbed, and small fleets. Tell us the trailer and we will say if it is a fit." },
      { question: "Will you force cheap freight to keep me moving?", answer: "No. Empty time is bad, but hauling below your floor is worse. We show deadhead and rate before you accept." },
      { question: "Do you handle detention?", answer: "We document delays and request accessorials with the broker while the clock is still running." },
      { question: "How fast can I start?", answer: "Once packets, insurance, and preferences are in, most trucks can be covered within a few days." },
    ],
  },
  related: [
    { label: "Lead Management", href: "/lead-management-services" },
    { label: "Appointments", href: "/appointment-scheduling-services" },
    { label: "Fast Food Solutions", href: "/fast-food-solutions" },
  ],
};

export const fastFoodPage: ServicePageContent = {
  crumb: "Fast Food Solutions",
  kicker: "Fast food operations support",
  formService: "Fast Food Solutions",
  seo: {
    title: "Fast Food Solutions | Smoother Rush Hours | HS Partners",
    description: "Fast food operations support for ordering, customer service, and rush-hour workflows that keep counters moving. Get a free store operations review from HS Partners.",
    keywords: "fast food solutions, restaurant customer support, QSR operations support, fast food call center, order support services, restaurant overflow support",
  },
  hero: {
    h1: "Fast Food Solutions That Keep Every Rush",
    h1Accent: "Moving Without Friction",
    intro: "Phones, delivery apps, and lobby tickets all spike at the same time. HS Partners provides fast food solutions that take overflow orders, customer issues, and follow-ups off the counter so your in-store team can cook, pack, and serve.",
    primaryCta: "Review Your Store Workflow",
    secondaryCta: "Talk to a QSR Specialist",
  },
  about: {
    kicker: "Built for busy counters",
    title: "What Are",
    titleAccent: "Fast Food Solutions?",
    paragraphs: [
      "Fast food solutions are outsourced support for the customer and order workflows around the kitchen: phone orders, app issues, complaints, catering requests, and after-hours questions. The grill stays in the store. The ringing phone does not have to.",
      "When cashiers are also the call center, tickets slow down and reviews get worse. HS Partners adds trained agents who know your menu rules, modifiers, and store hours so guests get answers without stopping the line.",
    ],
  },
  offerings: {
    kicker: "Front of house, off the floor",
    title: "Our Fast Food",
    titleAccent: "Solutions",
    intro: "We absorb the conversations that steal seconds from every ticket.",
    items: [
      { title: "Phone Order Support", description: "Overflow calls are answered with your menu, upsells, and store-specific 86 list so orders are accurate.", icon: "MessagesSquare" },
      { title: "Delivery App Exception Handling", description: "Missing items, wrong addresses, and driver issues are triaged instead of landing on a headset in the middle of a rush.", icon: "RefreshCcw" },
      { title: "Customer Recovery", description: "Complaints are logged, resolved to your policy, and escalated only when a manager is truly needed.", icon: "HeartPulse" },
      { title: "Catering and Large Orders", description: "Big tickets are captured completely — date, count, allergens, and pickup or delivery — before they hit the kitchen.", icon: "ClipboardCheck" },
      { title: "Hours, Menu, and Location Answers", description: "Simple questions never become a four-minute hold while someone is bagging fries.", icon: "Clock3" },
      { title: "Loyalty and Promo Help", description: "Code errors and app account issues are handled with approved scripts.", icon: "BadgeCheck" },
      { title: "Multi-Store Overflow", description: "One support layer can cover several locations with the right store routing.", icon: "Layers3" },
      { title: "After-Hours Coverage", description: "Late-night and early catering calls still get a human when the store phone is buried.", icon: "CalendarCheck" },
      { title: "Store-Level Reporting", description: "Call volume, order issues, and complaint themes are visible by location.", icon: "BarChart3" },
    ],
  },
  process: {
    title: "Our QSR Support Process:",
    titleAccent: "Step by Step",
    steps: [
      { number: "01", title: "Store listen-in", description: "We learn menu rules, 86 items, peak hours, and what managers want escalated." },
      { number: "02", title: "Playbook build", description: "Scripts, refund limits, and routing rules are written per location." },
      { number: "03", title: "Channel setup", description: "Phones, apps, and email overflow are connected, usually within 7 days." },
      { number: "04", title: "Rush coverage", description: "Agents take overflow so the counter can stay on tickets." },
      { number: "05", title: "Order accuracy checks", description: "Modifiers, allergens, and special instructions are repeated back before submission." },
      { number: "06", title: "Issue resolution", description: "Delivery and quality issues follow your compensation policy, not improvisation." },
      { number: "07", title: "Manager alerts", description: "Only true exceptions hit the store manager during service." },
      { number: "08", title: "Guest close-out", description: "The guest gets a clear next step instead of 'someone will call you back.'" },
      { number: "09", title: "Weekly store review", description: "Complaint themes and missed 86 items are fed back to operations." },
    ],
  },
  why: {
    title: "Why Operators Choose",
    titleAccent: "HS Partners",
    note: "Your crew runs the board. We run the conversations that used to steal the board.",
    items: [
      { title: "Menu-literate agents", description: "They learn your modifiers, combos, and what cannot be promised.", icon: "UtensilsCrossed" },
      { title: "Rush-hour overflow", description: "Coverage flexes when the headset is already too loud.", icon: "Clock3" },
      { title: "Policy, not freelancing", description: "Refunds and remakes follow the limits you set.", icon: "ShieldCheck" },
      { title: "Multi-unit ready", description: "Routing knows the store, the hours, and the 86 list.", icon: "Layers3" },
      { title: "Brand-safe tone", description: "Guests still feel like they reached the restaurant, not a generic call center.", icon: "MessagesSquare" },
      { title: "No long lock-in", description: "If ticket times and guest recovery do not improve, you should not stay.", icon: "BadgeCheck" },
    ],
  },
  results: {
    title: "Store Targets We Work Toward",
    caption: "Typical QSR guest-contact pain versus HS Partners targets",
    note: "Targets vary by brand, delivery mix, and whether phones are used for ordering.",
    averageLabel: "Typical Store Baseline",
    targetLabel: "Our Target for Your Shifts",
    rows: [
      { metric: "Abandoned phone orders", average: "High at rush", target: "Answered to your SLA" },
      { metric: "Manager interruptions", average: "Constant", target: "Exceptions only" },
      { metric: "Complaint handling time", average: "Next day", target: "Same shift when possible" },
      { metric: "Catering detail errors", average: "Recurring", target: "Captured before production" },
    ],
  },
  audiences: {
    kicker: "From one store to a group",
    title: "Fast Food Support",
    titleAccent: "by Format",
    intro: "QSRs, fast casual, and ghost kitchens fail in different places during a rush.",
    items: [
      "Quick-service restaurants",
      "Fast casual concepts",
      "Multi-unit franchise groups",
      "Ghost kitchens",
      "High-delivery stores",
      "Catering-heavy locations",
    ],
  },
  platforms: {
    kicker: "Works with your order stack",
    title: "POS and Delivery",
    titleAccent: "Integrations",
    intro: "We support the phones and apps your guests already use.",
    items: ["Toast", "Square", "Aloha", "DoorDash", "Uber Eats", "Grubhub", "Store phone trees"],
  },
  trust: {
    kicker: "Your brand on every call",
    title: "Guest Conversations You Can",
    titleAccent: "Stand Behind",
    body: "HS Partners agents use your name, menu, and refund policy. We do not invent promotions or override food-safety rules. Payment data stays in your POS or approved payment flow. Store-level access is limited to the information needed to complete the order or recovery.",
  },
  pricing: {
    title: "How Much Do Fast Food Support Services",
    titleAccent: "Cost?",
    body: "Pricing depends on store count, coverage hours, and whether we take orders or only handle issues. HS Partners offers monthly coverage or per-contact hybrid pricing with a written playbook and no surprise onboarding fees.",
    cta: "Request a Custom Quote",
  },
  start: {
    steps: [
      { number: "01", title: "Tell us where the rush breaks", description: "Phones, delivery apps, catering, or all three." },
      { number: "02", title: "Get a store review", description: "We show which conversations we can take off the counter first." },
      { number: "03", title: "Go live", description: "Playbooks and routing are live, usually within 7 days." },
    ],
    closerTitle: "Ready to Protect Ticket Times During the Rush?",
    closerCta: "Schedule Your Store Review",
  },
  faq: {
    titleAccent: "fast food solutions.",
    items: [
      { question: "Do you cook or deliver the food?", answer: "No. We support ordering, guest communication, and issue resolution. Your store still prepares and hands off the food." },
      { question: "Can you take phone orders during a rush?", answer: "Yes. Overflow order-taking is one of the highest-value uses, as long as we have your current menu and 86 list." },
      { question: "How do you keep orders accurate?", answer: "Modifiers and allergens are repeated back, store rules are in the playbook, and exceptions go to a manager only when required." },
      { question: "Can you cover more than one location?", answer: "Yes. Multi-store routing uses hours, menu differences, and the right store destination." },
      { question: "Will guests know they reached a support team?", answer: "We answer as your brand. The goal is a restaurant-quality conversation, not a generic call-center feel." },
      { question: "Do you work with DoorDash or Uber Eats issues?", answer: "Yes. Missing items, driver problems, and address errors can be triaged to your policy." },
      { question: "How fast can a store start?", answer: "Most locations go live within 7 days of playbook and menu access." },
      { question: "Is there a long contract?", answer: "We prefer to earn the coverage every month. Terms are stated clearly before launch." },
    ],
  },
  related: [
    { label: "Lead Management", href: "/lead-management-services" },
    { label: "Appointments", href: "/appointment-scheduling-services" },
    { label: "Truck Dispatching", href: "/truck-dispatching-services" },
  ],
};

export const appointmentsPage: ServicePageContent = {
  crumb: "Appointments",
  kicker: "Appointment scheduling services",
  formService: "Doctor–Patient Appointments",
  seo: {
    title: "Appointment Scheduling Services | Fewer No-Shows | HS Partners",
    description: "Doctor-patient appointment scheduling, reminders, and rescheduling support that fill calendars and reduce no-shows. Book a free scheduling review with HS Partners.",
    keywords: "appointment scheduling services, medical appointment scheduling, patient booking services, doctor appointment reminders, healthcare scheduling support, no-show reduction",
  },
  hero: {
    h1: "Appointment Scheduling Services That Turn First Contact Into",
    h1Accent: "Confirmed Visits",
    intro: "Empty slots and last-minute no-shows are often a communication problem, not a demand problem. HS Partners books, confirms, reminds, and reschedules doctor-patient appointments so calendars stay full and patients know exactly when to arrive.",
    primaryCta: "Review Your Schedule",
    secondaryCta: "Talk to a Booking Specialist",
  },
  about: {
    kicker: "Less waiting. More care.",
    title: "What Are Medical",
    titleAccent: "Appointment Services?",
    paragraphs: [
      "Appointment scheduling services cover inbound and outbound booking, insurance or referral checks at the slot level, reminders, waitlist fill, and rescheduling. The clinician's calendar stays the source of truth. Patients get a human path to a real time.",
      "When booking lives only on a voicemail or a portal nobody finishes, slots die. HS Partners gives practices a scheduling desk that answers, books to your rules, and works the waitlist when someone cancels.",
    ],
  },
  offerings: {
    kicker: "First call to arrival",
    title: "Our Appointment",
    titleAccent: "Services",
    intro: "We manage the full booking lifecycle, not just a confirmation text.",
    items: [
      { title: "Inbound Appointment Booking", description: "Calls and messages are converted into the correct visit type, provider, and duration using your templates.", icon: "CalendarCheck" },
      { title: "Outbound Recall and Waitlist", description: "Cancellations are backfilled from the waitlist and overdue patients are invited back.", icon: "RefreshCcw" },
      { title: "Smart Reminders", description: "SMS, phone, and email reminders include prep, location, and how to reschedule without abandoning the slot.", icon: "MessagesSquare" },
      { title: "Insurance and Referral Checks", description: "Visit types that need a referral or coverage note are flagged before the appointment is confirmed.", icon: "ClipboardCheck" },
      { title: "New Patient Scheduling", description: "Longer first visits, paperwork, and arriving-early instructions are built into the booking.", icon: "UserRoundCheck" },
      { title: "Reschedule and Cancel Handling", description: "Changes are processed against your notice rules and the open slot is offered out immediately.", icon: "Clock3" },
      { title: "Multi-Provider Calendars", description: "We book across providers and locations without double-booking or ignoring buffers.", icon: "Layers3" },
      { title: "No-Show Recovery", description: "Missed visits get a same-day or next-day outreach to rebook while the reason is still fresh.", icon: "HeartPulse" },
      { title: "Fill-Rate Reporting", description: "You see booked, confirmed, no-show, and waitlist fill by provider and visit type.", icon: "BarChart3" },
    ],
  },
  process: {
    title: "Our Scheduling Process:",
    titleAccent: "Step by Step",
    steps: [
      { number: "01", title: "Calendar rules review", description: "Visit types, buffers, new-patient blocks, and provider preferences are documented." },
      { number: "02", title: "Template design", description: "Booking scripts and reminder copy match how your practice actually runs." },
      { number: "03", title: "System connection", description: "We work inside your EHR or scheduling tool, usually within 7 days." },
      { number: "04", title: "Live booking", description: "Inbound demand is answered and booked to the correct slot." },
      { number: "05", title: "Confirmation", description: "Patients receive time, place, prep, and what to bring." },
      { number: "06", title: "Reminder cadence", description: "Reminders go out on a schedule that reduces no-shows without annoying patients." },
      { number: "07", title: "Same-day fill", description: "Cancellations are offered to the waitlist before the hole becomes a lost visit." },
      { number: "08", title: "No-show outreach", description: "Missed appointments are rebooked or documented with a reason." },
      { number: "09", title: "Monthly calendar review", description: "Fill rate and no-show patterns are reviewed with the practice manager." },
    ],
  },
  why: {
    title: "Why Practices Choose",
    titleAccent: "HS Partners",
    note: "Your providers see patients. We keep the calendar honest and full.",
    items: [
      { title: "Booked to your templates", description: "A new patient is never stuffed into a 10-minute follow-up slot.", icon: "CalendarCheck" },
      { title: "Waitlist that actually fills", description: "Openings are offered immediately, not discovered at 4 p.m.", icon: "RefreshCcw" },
      { title: "Prep in the reminder", description: "Patients arrive ready because the message said more than the time.", icon: "ClipboardCheck" },
      { title: "HIPAA-aware scheduling", description: "Minimum necessary information, secure channels, BAA when required.", icon: "Lock" },
      { title: "Works in your EHR", description: "Epic, Athena, eCW, and others — no forced new calendar.", icon: "Layers3" },
      { title: "Named scheduling lead", description: "One owner for rules, fill rate, and coverage hours.", icon: "BadgeCheck" },
    ],
  },
  results: {
    title: "Scheduling Targets We Work Toward",
    caption: "Typical practice scheduling metrics versus HS Partners targets",
    note: "Targets vary by specialty, new-patient mix, and how far out you book.",
    averageLabel: "Typical Practice Baseline",
    targetLabel: "Our Target for Your Calendar",
    rows: [
      { metric: "No-show rate", average: "10–20%", target: "Meaningfully reduced" },
      { metric: "Same-day unfilled cancellations", average: "Common", target: "Waitlist offered immediately" },
      { metric: "Unanswered booking calls", average: "High at lunch", target: "Covered during agreed hours" },
      { metric: "Wrong visit-type bookings", average: "Recurring", target: "Template-controlled" },
    ],
  },
  audiences: {
    kicker: "Any calendar that cannot stay empty",
    title: "Appointment Support",
    titleAccent: "by Practice",
    intro: "Primary care, specialists, and multi-location groups need different templates and reminder rules.",
    items: [
      "Primary care",
      "Specialty clinics",
      "Dental and allied health",
      "Behavioral health",
      "Imaging and diagnostics",
      "Multi-provider groups",
    ],
  },
  platforms: {
    kicker: "Your calendar stays the source of truth",
    title: "EHR and Scheduling",
    titleAccent: "Integrations",
    intro: "We book inside the system your front desk already trusts.",
    items: ["Epic", "Athenahealth", "eClinicalWorks", "NextGen", "Tebra", "DrChrono", "SimplePractice"],
  },
  trust: {
    kicker: "Patient data, handled carefully",
    title: "Scheduling Privacy You Can",
    titleAccent: "Trust",
    body: "Appointment details are protected health information. HS Partners follows HIPAA requirements, uses the minimum necessary data to book a visit, and can sign a Business Associate Agreement. We do not give clinical advice on scheduling calls; we book, confirm, and route urgent symptoms using your rules.",
  },
  pricing: {
    title: "How Much Do Appointment Scheduling Services",
    titleAccent: "Cost?",
    body: "Pricing depends on call volume, number of providers, and coverage hours. HS Partners offers monthly scheduling desk or per-booking hybrid pricing. Reminders, waitlist, and reporting are included in the written scope.",
    cta: "Request a Custom Quote",
  },
  start: {
    steps: [
      { number: "01", title: "Share the calendar pain", description: "No-shows, unanswered phones, or visit types that keep getting booked wrong." },
      { number: "02", title: "Get a scheduling review", description: "We show which templates, reminders, and waitlist rules will fill the week." },
      { number: "03", title: "Go live", description: "Your booking desk is connected and live, usually within 7 days." },
    ],
    closerTitle: "Ready for a Calendar Patients Actually Keep?",
    closerCta: "Schedule Your Booking Review",
  },
  faq: {
    titleAccent: "appointment scheduling.",
    items: [
      { question: "Can you book into our existing EHR?", answer: "Yes. We schedule inside your current system using your visit types, providers, and buffers." },
      { question: "Do you only send reminder texts?", answer: "No. Reminders are one piece. We also book, reschedule, fill cancellations, and recover no-shows." },
      { question: "How do you reduce no-shows?", answer: "Confirmation at booking, a reminder cadence with prep details, easy reschedule paths, and waitlist backfill when someone cancels." },
      { question: "Can you handle multiple providers and locations?", answer: "Yes. Templates control who can be booked where and for how long." },
      { question: "What if a caller has urgent symptoms?", answer: "We follow your escalation rules and do not give clinical advice. Urgent cases are routed the way your practice defines." },
      { question: "Is this HIPAA compliant?", answer: "Yes. We follow HIPAA, use approved channels, and sign a BAA when required." },
      { question: "Will this replace our receptionist?", answer: "It covers booking overflow and outbound recall so the front desk can help the patients already in the waiting room." },
      { question: "How quickly can we start?", answer: "Most practices go live within 7 days of calendar access and template approval." },
    ],
  },
  related: [
    { label: "Patient Screening", href: "/patient-screening-services" },
    { label: "Medical Billing", href: "/medical-billing-services" },
    { label: "Ultrasound Services", href: "/ultrasound-services" },
  ],
};
